// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package parser

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockParser creates a new instance of MockParser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockParser(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockParser {
	mock := &MockParser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockParser is an autogenerated mock type for the Parser type
type MockParser struct {
	mock.Mock
}

type MockParser_Expecter struct {
	mock *mock.Mock
}

func (_m *MockParser) EXPECT() *MockParser_Expecter {
	return &MockParser_Expecter{mock: &_m.Mock}
}

// Parse provides a mock function for the type MockParser
func (_mock *MockParser) Parse(s string) (*Command, error) {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for Parse")
	}

	var r0 *Command
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*Command, error)); ok {
		return returnFunc(s)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *Command); ok {
		r0 = returnFunc(s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Command)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockParser_Parse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Parse'
type MockParser_Parse_Call struct {
	*mock.Call
}

// Parse is a helper method to define mock.On call
//   - s string
func (_e *MockParser_Expecter) Parse(s interface{}) *MockParser_Parse_Call {
	return &MockParser_Parse_Call{Call: _e.mock.On("Parse", s)}
}

func (_c *MockParser_Parse_Call) Run(run func(s string)) *MockParser_Parse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockParser_Parse_Call) Return(command *Command, err error) *MockParser_Parse_Call {
	_c.Call.Return(command, err)
	return _c
}

func (_c *MockParser_Parse_Call) RunAndReturn(run func(s string) (*Command, error)) *MockParser_Parse_Call {
	_c.Call.Return(run)
	return _c
}
